name: template
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_ui_auth: ^3.0.0
  cloud_firestore: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
