// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQqCBTprbFC0gcoSqX1-EuDUpBqiZ1zo',
    appId: '1:911569460339:web:85ab467a89909c8ceb5e06',
    messagingSenderId: '911569460339',
    projectId: 'fir-417a1',
    authDomain: 'fir-417a1.firebaseapp.com',
    storageBucket: 'fir-417a1.firebasestorage.app',
    measurementId: 'G-GFXY3ZTD15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86lbmnLwgEJU36qP3gXRBHZ0_7DUkFBk',
    appId: '1:911569460339:android:573fe872f2cd8f09eb5e06',
    messagingSenderId: '911569460339',
    projectId: 'fir-417a1',
    storageBucket: 'fir-417a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4bF4eNaX6MRbgsL2AGcXr_SUZPtkrv2w',
    appId: '1:911569460339:ios:34f3e3e7e7f24a46eb5e06',
    messagingSenderId: '911569460339',
    projectId: 'fir-417a1',
    storageBucket: 'fir-417a1.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );

}