// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Z4f7IFNzZ479kyK2Rf3UkTsV791OwCk',
    appId: '1:195850488979:web:e299884f000c11e5165166',
    messagingSenderId: '195850488979',
    projectId: 'grupp-2-language',
    authDomain: 'grupp-2-language.firebaseapp.com',
    databaseURL: 'https://grupp-2-language-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grupp-2-language.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_CfMM6MW03AdVMp_dz0M2pVL8yaMckgk',
    appId: '1:195850488979:android:0c264855215f8e7e165166',
    messagingSenderId: '195850488979',
    projectId: 'grupp-2-language',
    databaseURL: 'https://grupp-2-language-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grupp-2-language.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNMX-G9Rkos3IxbXLnVxBVwLHfumtkj4E',
    appId: '1:195850488979:ios:e9b7686c9689e2a3165166',
    messagingSenderId: '195850488979',
    projectId: 'grupp-2-language',
    databaseURL: 'https://grupp-2-language-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grupp-2-language.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );

}